import GlobalBackGround from '@/components/GlobalBackGround'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Topbar from '@/components/topbar'
import Apps from '@/components/apps'
import Launchpad from '@/components/Launchpad'
import { SessionProvider } from 'next-auth/react';

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
  icons: '/apple.svg'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
